---

---

* On May 28, share your projects with the world


- Share your class, hackathon, or personal projects with Industry
  Professionals and fellow CUNY students
- Get professional feedback on your work and your presentation skills
- Build your professional network

* What is PitchFest?

PitchFest is a brand new CUNY event where selected CUNY students get to
present programming projects they have created for classes,
hackathons, or personal use to New York Tech Industry professionals to
receive vital feedback while building your network.

* How does PitchFest work?

Participants can enter using any programming project that will be
completed by the video demo deadline. It can be a personal project, a
project written at a hackathon, or a class project.

Teams and individuals can register using the link below. As part
of the application process, entrants must submit a linked to a short
video demonstration by *DATE*. Accepted entrants will be notified by
*DATE*. 

Prior to the event, PitchFest will host an optional Zoom based
coaching session to review best practices in project presentation.


At the event, entrants are required to bring a laptop with their
project. All entrants will be set up at tables. During the event,
industry professionals will visit tables and the participants have
five minutes to present to each group of professionals.

Refreshments will be provided during the event. 
* Restrictions:

The event site has limited capacity. Should number of entrants exceed
capacity, organizers will select final participants based on submitted
projects with preference going towards group submissions. 


#+begin_export html
<div id="details">
#+end_export>
* Details
** Registration deadline: May 12, 2025
** Video submission deadline: May 12, 2025
** Video submission instructions:
Make a short video demonstrating your project. This video does not
have to be a formal presentation, just something that shows that you
have a working project and what that project is and does.

Upload the project to an online location. For example, you could
upload it as an unlisted YouTube video.

Send an email to cunypitchfest@gmail.com with a subject of "PITCHFEST
VIDEO LINK." Include in the email your team name and a link to the
video.

** Event Date: May 28, 2025 5:00pm - 8:00pm 
** Location: CUNY@Amazon 12 West 39th Street, New York, NY

#+begin_export html
</div>
#+end_export>
* Questions?

Send any questions to cunypitchfest@gmail.com

* Register Here:

LINK

