---

---

* On January 15, share your projects with the world


- Share your class, hackathon, or personal projects with Industry
  Professionals and fellow CUNY students
- Get professional feedback on your work and your presentation skills
- Build your professional network

* What is PitchFest?

PitchFest is a brand new CUNY event where selected CUNY students get to
present programming projects they have created for classes,
hackathons, or personal use to New York Tech Industry professionals to
receive vital feedback while building your network.

* How does PitchFest work?

Participants can enter using any programming project that will be
completed by the video demo deadline. It can be a personal project, a
project written at a hackathon, or a class project.

Teams and individuals can register using the link below. As part
of the application process, entrants must submit a linked to a short
video demonstration by *January 8 2026*. Accepted entrants will be notified by
*January 12, 2026*. 

At the event, entrants are required to bring a laptop with their
project. All entrants will be set up at tables. During the event,
industry professionals will visit tables and the participants have
five minutes to present to each group of professionals.

Refreshments will be provided during the event. 
* Restrictions:

The event site has limited capacity. Should number of entrants exceed
capacity, organizers will select final participants based on submitted
projects with preference going towards group submissions. 

The event is also for CUNY students. Organizers will consider teams
composed of CUNY and non CUNY students as space permits.

#+begin_export html
<div id="details">
#+end_export>
* Details
** Registration deadline: January 8, 2026
** Video submission deadline: January 8, 2026
** Team Acceptances emailed by: January 12, 2026
** Event Date: January 15, 2026 5:00pm - 8:00pm
** Video submission instructions:
Make a short video demonstrating your project. This video does not
have to be a formal presentation, just something that shows that you
have a working project and what that project is and does.

Upload the project to an online location. For example, you could
upload it as an unlisted YouTube video.

Send an email to cunypitchfest@gmail.com with a subject of "PITCHFEST
VIDEO LINK." Include in the email your project name, primary contact
name and email  and a link to the video.

** Location: CUNY Central - 217 East 42nd Street
* Questions?

Send any questions to cunypitchfest@gmail.com

* Register Here:

To register, fill out this form by 1/8/2026: [[https://forms.gle/ZzbRKYAd3NkZzZhv8]]

And submit your video link by 1/8/2026.

